---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adanof06/aba.adan-office-services.com/app
    - export VENV=/home/adanof06/virtualenv/aba.adan-office-services.com/app/3.12
    - cd $DEPLOYPATH
    - $VENV/bin/pip install -r requirements.txt --quiet
    - $VENV/bin/python manage.py collectstatic --noinput
    - $VENV/bin/python manage.py migrate --run-syncdb
    - touch tmp/restart.txt
