---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adanof06/adan-office-services.com/temp_code
    - cd $DEPLOYPATH
    - pip install -r requirements.txt --quiet
    - python manage.py collectstatic --noinput
    - python manage.py migrate --run-syncdb
    - touch tmp/restart.txt
