# Generated by Django 5.2.10 on 2026-03-10 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duffel_order_id', models.CharField(max_length=100, unique=True)),
                ('booking_reference', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('departure_date', models.DateField()),
                ('airline', models.CharField(blank=True, max_length=100)),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('cabin_class', models.CharField(blank=True, max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duffel_passenger_id', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('born_on', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='vols.booking')),
            ],
        ),
    ]
