# Generated by Django 6.0.3 on 2026-03-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('hotel_name', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=100)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.PositiveIntegerField(default=1)),
                ('adults', models.PositiveIntegerField(default=2)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Agoda real price', max_digits=10)),
                ('markup_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('markup_amount', models.DecimalField(decimal_places=2, help_text='Your profit', max_digits=10)),
                ('customer_price', models.DecimalField(decimal_places=2, help_text='Price charged to customer', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('agoda_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
