# Generated by Django 6.0.3 on 2026-03-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vols', '0002_hotelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='confirmed', max_length=20),
        ),
    ]
