# Generated by Django 6.0.3 on 2026-03-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vols', '0003_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='markup_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
