# Generated by Django 6.0.3 on 2026-08-13 11:40

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_playstore_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='playstore').exists():
        User.objects.create(
            username='playstore',
            email='playstore@example.com',
            password=make_password('GooglePlay123!')
        )

class Migration(migrations.Migration):

    dependencies = [
        ('vols', '0005_rename_agoda_ref_hotelbooking_partner_ref_and_more'),
    ]

    operations = [
        migrations.RunPython(create_playstore_user),
    ]
